name: Build PGEdge PostgreSQL Packages

on:
  workflow_dispatch:
    inputs:
      pg_version:
        description: 'PostgreSQL version to build (e.g., 17.5)'
        required: true
        default: '17.5'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: rockylinux:8
            arch: amd64
          - image: rockylinux:8
            arch: arm64
          - image: rockylinux:9
            arch: amd64
          - image: rockylinux:9
            arch: arm64
          - image: debian:bullseye
            arch: amd64
          - image: debian:bullseye
            arch: arm64
          - image: debian:bookworm
            arch: amd64
          - image: debian:bookworm
            arch: arm64
          - image: ubuntu:jammy
            arch: amd64
          - image: ubuntu:jammy
            arch: arm64
          - image: ubuntu:noble
            arch: amd64
          - image: ubuntu:noble
            arch: arm64

    name: Build on ${{ matrix.image }} (${{ matrix.arch }})
    steps:
      - name: Checkout pgedge-postgresql source
        uses: actions/checkout@v4

      - name: Run PGEdge Builder Action
        uses: maqeel75/pgedge-builder-action@main
        with:
          image: ${{ matrix.image }}
          arch: ${{ matrix.arch }}
          pg_version: ${{ inputs.pg_version }}

